# Generated by Django 3.0 on 2021-12-01 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criptos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cripto', models.CharField(max_length=100, verbose_name='Nome da Cripto')),
                ('valor_atual_cripto', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'Criptomoeda',
            },
        ),
    ]
