# Generated by Django 3.0 on 2021-12-01 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cripto', '0003_categorycripto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criptos',
            old_name='nome_cripto',
            new_name='name_cripto',
        ),
        migrations.RenameField(
            model_name='criptos',
            old_name='valor_atual_cripto',
            new_name='value_current_cripto',
        ),
    ]
