# Generated by Django 3.0 on 2021-12-01 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0004_auto_20211201_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='criptos',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crypto.CategoryCripto'),
        ),
    ]
