# Generated by Django 3.0 on 2021-12-02 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0006_auto_20211201_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Active',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('name_crypto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crypto.Crypto')),
            ],
            options={
                'verbose_name_plural': 'Ativos Comprados',
            },
        ),
    ]
