# Generated by Django 3.0 on 2021-12-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0008_active_unitary_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='active',
            name='quantity_crypto',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
        ),
    ]
