# Generated by Django 3.0 on 2021-12-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0009_active_quantity_crypto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active',
            name='quantity_crypto',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
    ]
