# Generated by Django 3.0 on 2021-12-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0011_auto_20211202_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active',
            name='quantity_crypto',
            field=models.DecimalField(decimal_places=15, max_digits=19),
        ),
    ]
