# Generated by Django 3.0 on 2021-10-17 00:42

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_post', models.CharField(max_length=255)),
                ('data_post', models.DateTimeField(default=django.utils.timezone.now)),
                ('conteudo_post', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('excerto_post', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('imagem_post', models.ImageField(blank=True, upload_to='post_img/%Y/%m/%d')),
                ('publicado_post', models.BooleanField(default=False)),
                ('restricao_post', models.CharField(choices=[('Público', 'Publico'), ('Privado', 'Privado')], max_length=7)),
                ('autor_post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('categoria_post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Topicos')),
            ],
            options={
                'verbose_name_plural': 'Post',
            },
        ),
    ]
