# Generated by Django 3.0 on 2021-10-19 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=1, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
