# Generated by Django 3.0 on 2021-10-29 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_comentarios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentarios',
            options={'verbose_name': 'Comentário', 'verbose_name_plural': 'Comentários'},
        ),
    ]
